### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by AL-HAYALI** [cgoldberg/py-slideshow#2]
Hi, Thanks for the code, I have faced the following issue while trying to run it.

Traceback (most recent call last):
  File "C:\Users\UserName\Desktop\slideshow\py-slideshow\slideshow.py", line 80, in <module>
    img = pyglet.image.load(random.choice(image_paths))
  File "C:\Python39\lib\random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

Any Ideas?

**Comment by AL-HAYALI** [comment]
Solved by putting the image files the I want to run inside image folder which is already there with the program.
